version: '3'
services:
  builder:
    build: ./docker/builder
    ports:
    - "2345:2345"
    volumes:
    - ./:/host
    - ./config/pgarrow.yml:/etc/pgarrow/config.yaml
  postgres:
    #image: postgres
    image: postgres:11
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']
    environment:
      POSTGRES_PASSWORD: pgarrow
    ports:
    - '5432:5432'
    volumes:
    - ./:/host
    - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      ALLOW_ANONYMOUS_LOGIN: yes
#    networks:
#      - app-tier
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
#      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
#     KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#    depends_on:
#      - zookeeper
  pgarrowkafka:
    environment:
      PGDATABASE: src
      PGARROW_DIRECTION: pgarrowkafka
    image: mannemsolutions/pgarrow
    volumes:
    - ./config/pgarrow.yml:/etc/pgarrow/config.yaml
  kafkaarrowpg:
    environment:
      PGDATABASE: dest
      PGARROW_DIRECTION: kafkaarrowpg
    image: mannemsolutions/pgarrow
    volumes:
    - ./config/pgarrow.yml:/etc/pgarrow/config.yaml
  rabbit:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: arrow
      RABBITMQ_DEFAULT_PASS: arrow
    ports:
    - "5672"
    - "15672"
  pgarrowrabbit:
    environment:
      PGDATABASE: src
      PGARROW_DIRECTION: pgarrowrabbit
    image: mannemsolutions/pgarrow
    volumes:
    - ./config/pgarrow.yml:/etc/pgarrow/config.yaml
  rabbitarrowpg:
    environment:
      PGDATABASE: dest
      PGARROW_DIRECTION: rabbitarrowpg
    image: mannemsolutions/pgarrow
    volumes:
    - ./config/pgarrow.yml:/etc/pgarrow/config.yaml
