---
debug: true
kafka_config:
  brokers:
    - "kafka:9092"
pg_config:
  dsn:
    password: pgarrow
    user: postgres
    host: postgres
  skip_errors:
    23505: duplicate key value violates unique constraint
rabbit_config:
  url: amqp://arrow:arrow@rabbit:5672/
